Add support for visual regression testing
AlaskaAirlines/auro-input pull request #104
Opened 2021-12-10 23:56 UTC by blackfalcon

Changes to be committed:
new file:   backstop.json
modified:   demo/demo.md

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

This is a POC pull request to test out the concept of using BackstopJS as a visual regression tool. 

## To use

To use this POC

1. Pull down the branch
1. run `$ npm ci`
1. Run `$ npm run dev`
1. run `$ backstop test` to run a test and see the CLI report 
1. Make an edit in the HTML or Sass
1. run `$ backstop test` to see the diff
1. run `$ backstop openReport` to see the visual diff

## Discoveries 

1. Using a visual regression tool creates a lot of additional assets that will bloat the size of the repo over time
1. A cleaning strategy will need to be discussed 
1. While this and other snapshot tools are able to get a capture of the demo itself, there are issues with interactions due to BackstopJs not being able to find selectors inside the shadow DOM

## Opportunty 

Running a visual regression test suite will help us ensure that each release will maintain the correct visual experience unless there is an expected change. It is assumed that this would run as a pre-commit hook

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [x] Other (poc)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-12-12 22:28 UTC, blackfalcon commented
Updates to this PR/POC include using PlayWrite versus Puppeteer which now allows for full scenario support for shadowDOM elements. 

More information on using scenarios https://github.com/garris/BackstopJS#using-backstopjs

The latest commit adds support for testing in the Husky pre-commit. New npm scripts include `vrt:test` and `vrt:approve`. 

`vrt` === "visual regression testing". No need to bind scripts to specific libraries. This frees us to change things up down the road and not have to change core scripts.

2021-12-15 21:52 UTC, blackfalcon commented
Given the scope of this PR, I want to consider how we can support this as an individual update to retrofit legacy repos and not have to depend on a full repo upgrade.

2021-12-16 17:43 UTC, blackfalcon commented
There are issues with running this check in the remote. The tool needs to check the reference version against a URL. Locally we can use `localhost:8000`, but there is no server running in the remote so this check simply failed. 

https://github.com/AlaskaAirlines/auro-input/runs/4551032861?check_suite_focus=true#step:5:97

digging more into this, the solution is to have a docker container. While I can agree with this in a use case where there is a large app with many test scenarios, but adding docker support for these element repos is overkill IMHO. 

To that end, running the vrt tests locally is the current plan and as discussed, with the removal of the ES5 bundler and that these UI tests take < 5 seconds to run, I don't see this as a major burden with a pre-commit hook.

2021-12-16 23:00 UTC, blackfalcon commented
@geoffrich the PR has been updated, please pull and re-run the tests. All should be green this time.

2021-12-17 00:59 UTC, blackfalcon commented
@jason-capsule42, @geoffrich and I have gone over this POC and it is in solid working order. If you could pull the branch and run locally, I'd appreciate it. Please add any feedback as needed.

2021-12-17 16:27 UTC, geoffrich reviewed
Just some comments about unnecessary files.

2021-12-17 16:27 UTC, geoffrich commented on backstop.json
> +      "postInteractionWait": 0,
Are these the default values for a lot of these? Would be good to try to slim some of these scenarios down if possible.

2021-12-17 16:27 UTC, geoffrich commented on backstop_data/engine_scripts/cookies.json
> +[
Probably don't need this file since Auro doesn't need cookies.

2021-12-17 16:27 UTC, geoffrich commented on backstop_data/engine_scripts/playwright/interceptImages.js
> +/**
Are we using this?

2021-12-17 16:27 UTC, geoffrich commented on backstop_data/engine_scripts/playwright/onBefore.js
> +module.exports = async (page, scenario, viewport, isReference, browserContext) => {
Can likely remove if we don't need cookies.

2021-12-17 16:27 UTC, geoffrich commented on backstop_data/engine_scripts/playwright/overrideCSS.js
> +/**
Do we need this?

2021-12-17 16:27 UTC, geoffrich commented on backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
> +module.exports = async (page, scenario) => {
We're using playwright, yeah? So everything in `backstop_data/engine_scripts/puppet` can be removed.

2021-12-18 21:43 UTC, blackfalcon commented
Recent updates including shedding some file weight and updating settings to increase speed and performance of vrt.

2022-01-10 19:25 UTC, jason-capsule42 submitted a review, later dismissed

2022-01-31 20:58 UTC, jason-capsule42 requested changes
The tests aren't running correctly for me.

1. Pull down the latest of the branch
1. `npm i`
1. `npm run vrt:test`

Results
```
jasonbaker@SEAHGMJBAKER auro-input % npm run vrt:test

> @aurodesignsystem/auro-input@2.1.2 vrt:test /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input
> backstop test

BackstopJS v6.0.4
Loading config:  /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop.json 

COMMAND | Executing core for "test"
createBitmaps | Selected 9 of 9 scenarios.
Browser Console Log 0: []
Browser Console Log 0: []
Browser Console Log 0: []
Browser Console Log 0: []
Browser Console Log 0: []
Browser Console Log 0: []
Browser Console Log 0: []
Browser Console Log 0: BackstopTools have been installed.
Browser Console Log 0: []
Browser Console Log 0: []
Browser Console Log 0: BackstopTools have been installed.
Browser Console Log 0: BackstopTools have been installed.
Browser Console Log 0: BackstopTools have been installed.
Browser Console Log 0: BackstopTools have been installed.
Browser Console Log 0: BackstopTools have been installed.
Browser Console Log 0: BackstopTools have been installed.
SCENARIO > date
SCENARIO > creditcardClick2
Browser Console Log 0: BackstopTools have been installed.
Browser Console Log 0: BackstopTools have been installed.
SCENARIO > default
Element not found for capturing: #demo1
Element not found for capturing: #demo2
x Close Browser
SCENARIO > error
Element not found for capturing: #error1
Element not found for capturing: #error2
x Close Browser
SCENARIO > creditcardClick
SCENARIO > emailRequiredError
SCENARIO > click2
SCENARIO > creditcard
SCENARIO > click
Element not found for capturing: #demo13
Element not found for capturing: #demo14
x Close Browser
Playwright encountered an error while running scenario "date"
TimeoutError: page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#demo15" to be visible
============================================================
Playwright encountered an error while running scenario "creditcardClick2"
TimeoutError: page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#demo14" to be visible
============================================================
Playwright encountered an error while running scenario "creditcardClick"
TimeoutError: page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#demo13" to be visible
============================================================
Playwright encountered an error while running scenario "emailRequiredError"
TimeoutError: page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#demo9" to be visible
============================================================
Playwright encountered an error while running scenario "click2"
TimeoutError: page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#demo2" to be visible
============================================================
Playwright encountered an error while running scenario "click"
TimeoutError: page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#demo1" to be visible
============================================================
      COMMAND | Executing core for "report"
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_click_0_demo1_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_default_0_demo1_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_default_1_demo2_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_click2_0_demo2_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_error_0_error1_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_emailRequiredError_0_demo9_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_error_1_error2_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_creditcard_0_demo13_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 30.64%, threshold: 10% }: creditcard auro-input_creditcard_0_demo13_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 23.18%, threshold: 10% }: default auro-input_default_0_demo1_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 23.23%, threshold: 10% }: default auro-input_default_1_demo2_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 34.17%, threshold: 10% }: click auro-input_click_0_demo1_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_creditcardClick_0_demo13_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 30.65%, threshold: 10% }: error auro-input_error_0_error1_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 34.27%, threshold: 10% }: click2 auro-input_click2_0_demo2_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_creditcard_1_demo14_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_date_0_demo15_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 30.71%, threshold: 10% }: error auro-input_error_1_error2_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 45.18%, threshold: 10% }: emailRequiredError auro-input_emailRequiredError_0_demo9_0_tablet.png
   See: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/failed_diff_auro-input_creditcardClick2_0_demo14_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 45.17%, threshold: 10% }: creditcardClick auro-input_creditcardClick_0_demo13_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 30.69%, threshold: 10% }: creditcard auro-input_creditcard_1_demo14_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 34.17%, threshold: 10% }: date auro-input_date_0_demo15_0_tablet.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 45.30%, threshold: 10% }: creditcardClick2 auro-input_creditcardClick2_0_demo14_0_tablet.png
       report | Test completed...
       report | 0 Passed
       report | 12 Failed
       report | Writing browser report
       report | Resources copied
       report | Copied json report to: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/bitmaps_test/20220131-125558/report.json
       report | Copied jsonp report to: /Users/jasonbaker/Development/AlaskaAir/AlaskaAirlines/auro-input/backstop_data/html_report/ [...]

2022-01-31 23:44 UTC, blackfalcon commented
@jason-capsule42 , do you have a server running? 

1. pull branch
2. run `npm ci`
3. run `npm run dev`
4. run `npm run vrt:test`

2022-02-02 05:50 UTC, jason-capsule42 approved these changes

2022-02-03 07:26 UTC, merged

2022-02-03 07:40 UTC, blackfalcon commented
:tada: This PR is included in version 2.1.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-input/v/2.1.3)
- [GitHub release](https://github.com/AlaskaAirlines/auro-input/releases/tag/v2.1.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: