Fix auto cursor placement for keyboard input for datepicker
AlaskaAirlines/auro-input pull request #183
Opened 2022-09-15 04:41 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #181 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

When the user has a valid date in the datepicker input and then exclusively uses the keyboard to change the date, the cursor placed by the user now stays in place, rather than automatically moving to the end of the date input string.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-09-16 14:47 UTC, blackfalcon requested changes

2022-09-16 14:47 UTC, blackfalcon commented on src/base-input.js
> +
I see that you have addressed the issue with the initial cursor placement and this does allow the user to change that one value. Then we run into that issue with Cleave trying to format the data.

2022-09-19 16:20 UTC, jason-capsule42 requested changes
Needs to handle Autoformatting from CleaveJS

2022-09-19 16:20 UTC, jason-capsule42 commented on src/base-input.js
> +
This isn't handling when CleaveJS is auto-formatting the input. I have an idea. Let's do some pair-programming today.

2022-09-21 17:26 UTC, blackfalcon submitted a review, later dismissed
I am typing in the following date `4121973`

![Sep-21-2022 10-25-11](https://user-images.githubusercontent.com/181089/191571035-7607a26f-46fa-43a6-910e-5fe9811e7586.gif)

2022-09-21 21:59 UTC, blackfalcon approved these changes
This update is 99.999% successful. The only remaining edge case I discovered is if you were to put in a date like `04/12/1988` and then to change the `04` to `12` the ONLY way to make that happen is to highlight the `04` and then type `12`. Anything else causes chaos between cursor placement and auto-formatting. 

But this is an edge case. If this were to come up as customer feedback, then we can talk about the nuclear option.

2022-09-21 22:08 UTC, jason-capsule42 approved these changes

2022-09-21 22:09 UTC, merged

2022-09-21 22:12 UTC, blackfalcon commented
:tada: This PR is included in version 2.9.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-input/v/2.9.1)
- [GitHub release](https://github.com/AlaskaAirlines/auro-input/releases/tag/v2.9.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: