Node 18+ updates #21
AlaskaAirlines/auro-input pull request #253
Opened 2023-05-08 05:11 UTC by fajar-apri-alaska

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #248 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-05-09 20:58 UTC, blackfalcon requested changes

2023-05-09 20:58 UTC, blackfalcon commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +	        4. See error
Too many spaces/tabs

2023-05-09 20:58 UTC, blackfalcon commented on .github/settings.yml
> +    description: This Issue or Pull Request already exists
```suggestion
  - name: auro-input
    color: 'fa23e4'
    description:
    process: Key filter for this repo
  - name: duplicate
    color: '156fad'
    description: This Issue or Pull Request already exists
```

2023-05-09 20:58 UTC, blackfalcon commented on .github/workflows/testPublish.yml
> +      - run: npm test
```suggestion
      - run: npm run build
```

2023-05-09 20:58 UTC, blackfalcon commented on .github/workflows/testPublish.yml
> +      - run: npm run bundler
```suggestion
      - run: npm run build
```

2023-05-09 20:58 UTC, blackfalcon commented on .github/workflows/testPublish.yml
> +      - run: npm run bundler
```suggestion
      - run: npm run build
```

2023-05-09 20:58 UTC, blackfalcon commented on package.json
> +    "sass": "^1.62.1",
add

https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/package.json#L75-L79

2023-05-09 20:58 UTC, blackfalcon commented on scripts/postCss.mjs
> +
Please update file to be like the following 

https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/scripts/postCss.js

2023-05-09 20:58 UTC, blackfalcon commented on scripts/pre-commit.mjs
> +import chalk from 'chalk';
Update file to be like the following 

https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/scripts/pre-commit.mjs

2023-05-10 21:59 UTC, blackfalcon commented
@fajar-apri-alaska please see new issue for missing updates

https://github.com/AlaskaAirlines/auro-input/issues/254

2023-05-10 22:00 UTC, blackfalcon requested changes
See additional comments.

2023-05-11 14:16 UTC, fajar-apri-alaska commented
> @fajar-apri-alaska please see new issue for missing updates
> 
> * [Missing updates for Node 18+ support  #254](https://github.com/AlaskaAirlines/auro-input/issues/254)

Thanks for addressing the missing updates ~

2023-05-11 22:36 UTC, blackfalcon approved these changes

2023-05-11 22:38 UTC, merged

2023-05-11 22:42 UTC, blackfalcon commented
:tada: This PR is included in version 2.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-input/v/2.14.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-input/releases/tag/v2.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: